config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end

  def authenticate_user
    if logged_in?
      unless current_user.id == @blog.user_id
        flash[:notice] = "権限がありません"
        redirect_to blogs_path
      end
    else
      redirect_to new_user_path, notice:"ログインが必要です"
    end
  end

  def ensure_current_user
    if logged_in?
      unless current_user.id == params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to blogs_path
      end
    else
      redirect_to new_user_path, notice: "ログインが必要です"
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy ]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
      @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    if logged_in?
      @favorite = current_user.favorites.find_by(user_id: @user_id)
    else
      record_to new_user_path, notice: 'ログインが必要です'
    end
  end

  def new
    @blog = Blog.new
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def edit; end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    elsif @blog.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to blogs_path, notice: '投稿しました'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: '投稿を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: '投稿を削除しました'
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:image, :image_cache, :content, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.all
  end

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: '編集しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :画像： %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :内容： %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "投稿", class: "send" %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :content %>
  <p>内容：<%= @blog.content %></p>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model: @blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to '詳細', @blog %> |
<%= link_to '一覧へ戻る', blogs_path %>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>

<table>
  <thead>
    <tr>
      <th>内容</th>
      <th>ユーザー</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.content %></td>
        <td><%= blog.user.name %></td>
        <td><%= link_to '詳細', blog %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'お気に入り一覧へ', favorites_path %>
<%= link_to '投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h1>新しい投稿</h1>

<%= render 'form', blog: @blog %>

<%= link_to '一覧へ戻る', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user.name %>
</p>

  <% unless @blog.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>

  <% if @blog.user_id == current_user.id %>
    <%= link_to '編集', edit_blog_path %> <%= link_to '一覧', blogs_path %> <%= link_to '削除', @blog, method: :delete, data: { confirm: '消しても良いの?' } %>
  <% else %>
    <%= link_to '一覧へ', blogs_path %>
  <% end %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お気に入り一覧</h1>

<table>
  <thead>
    <tr>
      <th>内容</th>
      <th>お気に入りした人</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.blog.content %></td>
        <td><%= favorite.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '一覧へ戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExamClone3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <header id="header">
    <p>Weird instagram</p>
      <% if logged_in? %>
        <%= link_to "マイページ", user_path(current_user.id) %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "新規登録", new_user_path %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>
    </header>

    <% flash.each do |key, value|%>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <div id="body">
    <%= yield %>
    </div>

    <div id="footer">Weird instagram</div>

  </body>

</html>

app/views/users/edit.html.erb
<h1>編集画面</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <div class = "new-form">
      <%= f.label :名前 %>
      <%= f.text_field :name %>
      <%= f.label :メールアドレス %>
      <%= f.email_field :email %>
      <%= f.label :画像 %>
      <%= f.file_field :image %>
      <%= f.label :紹介文 %>
      <%= f.text_area :content %>
      <%= f.label :パスワード %>
      <%= f.password_field :password %>
      <%= f.label :パスワード確認 %>
      <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "編集する", class: "send"%>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <div class = "new-form">
      <%= f.label :名前 %>
      <%= f.text_field :name %>
      <%= f.label :メールアドレス %>
      <%= f.email_field :email %>
      <%= f.label :パスワード %>
      <%= f.password_field :password %>
      <%= f.label :パスワード確認 %>
      <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "作成する", class: "send"%>
<% end %>

<% if @user.errors.any? %>
<div id = "error_explanation">
  <h2><%= pluralize(@user.errors.count,"error") %> prohibited this <%= @user.name %> from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<%= link_to '投稿一覧', blogs_path %>
<%= link_to  '新規投稿', new_blog_path %>
<h1>名前：<%= @user.name%></h1>
<p>メールアドレス：<%= @user.email %></p>
<p>プロフィール画像： <%= image_tag(@user.image.url) if @user.image && @user.image.url %></p>
<p>自己紹介：<%= @user.content %></p>
<%= link_to 'プロフィール編集', edit_user_path %>